version: '3.8'

services:
  app:
    image: ghcr.io/valentinlutz/coding-dojo-api-golang:latest
    build:
      context: ../
      dockerfile: app/Dockerfile
    command: ["./app", "-port", "8080", "-memory", "false"]
    container_name: app
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 250M

# postgres: 
#   image: postgres:14.2
#   container_name: postgres
#   environment:
#     POSTGRES_DB: test
#     POSTGRES_USER: test
#     POSTGRES_PASSWORD: test
#   ports:
#     - '5432:5432'
