apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: test
    jsonData:
      version: Flux
      organization: monke
      defaultBucket: coding_dojo