FROM amazoncorretto:17-alpine3.17-jdk AS builder
WORKDIR /build
COPY app/.mvn/ ./.mvn
COPY app/mvnw ./
COPY app/pom.xml ./
RUN ./mvnw dependency:go-offline
COPY app/src ./src
RUN ./mvnw package -offline


FROM amazoncorretto:17-alpine3.17-jdk
COPY --from=builder /build/target/appspring-1.0.0-SNAPSHOT.jar /deployments/sprinng-run.jar
CMD ["java", "-jar", "/deployments/spring-run.jar"]


