openapi: 3.0.3
info:
  title: Task API
  version: 0.0.1

paths:
  /tasks:
    get:
      operationId: getTasks
      summary: Returns a list of tasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tasks_response"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
    post:
      operationId: createTask
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_request"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"

  /tasks/{task_id}:
    get:
      operationId: getTask
      summary: Return task with task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
    put:
      operationId: updateTask
      summary: Replace task with task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_request"
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
    delete:
      operationId: deleteTask
      summary: Delete task with task id
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error_response"
components:
  schemas:
    error_response:
      type: object
      required:
        - method
        - path
        - timestamp
        - code
      properties:
        method:
          type: string
          example: GET
        path:
          type: string
          example: /tasks
        timestamp:
          type: string
          format: date-time
        code:
          type: integer
          example: 9001
        message:
          type: string
          example: panic it's over 9000
    task_response:
      properties:
        title:
          type: string
          example: Lorem ipsum dolor
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed dia
        task_id:
          type: string
          example: 4f6b3bf7-21a7-4b43-ba74-e9e442e875a2
          format: uuid
      required:
        - task_id
        - title
    tasks_response:
      type: array
      items:
        $ref: "#/components/schemas/task_response"
    task_request:
      properties:
        title:
          type: string
          example: Lorem ipsum dolor
        description:
          type: string
          example: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed dia
      required:
        - title
