version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: app/src/main/docker/Dockerfile.jvm
    image: harbor.doubleslash.de/coding-dojo-stuttgart/task-app-java-spring-webflux:latest
    container_name: coding_dojo_app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      USE_IN_MEMORY: false
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'
    depends_on:
     db:
       condition: service_healthy

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5