version: '3.8'

services:

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
    volumes:
      - ./grafana:/etc/grafana/provisioning/:ro

  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: test
      DOCKER_INFLUXDB_INIT_PASSWORD: testtest
      DOCKER_INFLUXDB_INIT_ORG: monke
      DOCKER_INFLUXDB_INIT_BUCKET: coding_dojo
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: test
    volumes:
      - ./influxdb2:/var/lib/influxdb2
