version: '3.8'

services:

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
    volumes:
      - ./grafana:/etc/grafana/provisioning/:ro

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/prometheus/prometheus.yml:ro
      - ./prometheus/data/:/prometheus/data/:rw
