version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: test
      GF_SECURITY_ADMIN_PASSWORD: test
    volumes:
      - ./grafana:/etc/grafana/provisioning/:ro

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/prometheus/prometheus.yml:ro
      - ./prometheus/data/:/prometheus/data/:rw

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "7070:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
