version: '3.8'

services:
  app:
    image: harbor.doubleslash.de/coding-dojo-stuttgart/${APP_NAME}:latest
    container_name: ${TEST_ID}
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      USE_IN_MEMORY: ${USE_MEMORY}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.3-alpine3.17
    container_name: db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 5s
      timeout: 5s
      retries: 5